sudo: required

language: node_js
node_js:
  - "8"

addons:
  postgresql: "10"
  apt:
    packages:
      - docker-ce
      - postgresql-10
      - postgresql-client-10

cache:
  directories:
    - node_modules/

services:
  - docker
  - postgresql

env:
  global:
    - DOCKER_USERNAME=travisrekry18
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  matrix:
    - PROJECT_DIR=server
      DOCKER_IMAGE=rekrysofta/recruitmenttool_server
    - PROJECT_DIR=client
      DOCKER_IMAGE=rekrysofta/recruitmenttool_client

stages:
  - name: script
    env:
      - NODE_ENV=development
  - name: deploy
    if: branch = master
    env:
      - NODE_ENV=production

install: true

before_script: chmod +x scripts/setup_database.sh && scripts/setup_database.sh

script: cd $PROJECT_DIR && npm install && npm run lint && npm test

deploy:
  provider: script
  script: chmod +x ../scripts/deploy-k8s.sh && ../scripts/deploy-k8s.sh
  skip_cleanup: true
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_127facfaf176_key -iv $encrypted_127facfaf176_iv
  -in gke-service-account.json.enc -out gke-service-account.json -d
