sudo: required

language: node_js
node_js:
  - "8"

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules/

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=travisrekry18
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  matrix:
    - PROJECT_DIR=server
      DOCKER_IMAGE=rekrysofta/recruitmenttool_server
      K8S_DEPLOYMENT_NAME=recruitment-tool-server
    - PROJECT_DIR=client
      DOCKER_IMAGE=rekrysofta/recruitmenttool_client
      K8S_DEPLOYMENT_NAME=recruitment-tool-client

stages:
  - name: script
    env:
      - NODE_ENV=development
  - name: deploy
    if: branch = master
    env:
      - NODE_ENV=production

install: true

script: cd $PROJECT_DIR && npm install && npm run lint && npm test

deploy:
  provider: script
  script: chmod +x ../scripts/deploy-k8s.sh && ../scripts/deploy-k8s.sh
  skip_cleanup: true
  on:
    branch: master
