sudo: required

language: node_js
node_js:
  - "8"

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules/

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=travisrekry18
    - NODE_ENV=production
  matrix:
    - PROJECT_DIR=server
      DOCKER_IMAGE=rekrysofta/recruitmenttool_server
    - PROJECT_DIR=client
      DOCKER_IMAGE=rekrysofta/recruitmenttool_client

stages:
  - name: deploy
    if: branch = master

install: true

script: cd $PROJECT_DIR && npm install && npm test && docker build -t ${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER} .

before_deploy: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

deploy:
  provider: script
  script: cd $PROJECT_DIR && docker push ${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}
  on:
    branch: master
