sudo: required

language: node_js
node_js:
  - "8"

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules/

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=travisrekry18
  matrix:
    - PROJECT_DIR=server
      DOCKER_IMAGE=rekrysofta/recruitmenttool_server
    - PROJECT_DIR=client
      DOCKER_IMAGE=rekrysofta/recruitmenttool_client

stages:
  - name: script
    env:
      - NODE_ENV=development
  - name: deploy
    if: branch = master
    env:
      - NODE_ENV=production

install: true

script: cd $PROJECT_DIR && npm install && npm test

before_deploy: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: npm prune --production && docker build -t ${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER} . && docker push ${DOCKER_IMAGE}:${TRAVIS_BUILD_NUMBER}
  on:
    branch: master
before_install:
- openssl aes-256-cbc -K $encrypted_127facfaf176_key -iv $encrypted_127facfaf176_iv
  -in gke-service-account.json.enc -out gke-service-account.json -d
