sudo: required

language: node_js
node_js:
  - "8"

addons:
  apt:
    packages:
      - docker-ce

cache:
  directories:
    - node_modules/
    - ${HOME}/google-cloud-sdk/

services:
  - docker

env:
  global:
    - DOCKER_USERNAME=travisrekry18
  matrix:
    - PROJECT_DIR=server
      DOCKER_IMAGE=rekrysofta/recruitmenttool_server
      K8S_DEPLOYMENT_NAME=recruitment-tool-server
    - PROJECT_DIR=client
      DOCKER_IMAGE=rekrysofta/recruitmenttool_client
      K8S_DEPLOYMENT_NAME=recruitment-tool-client

stages:
  - name: script
    env:
      - NODE_ENV=development
  - name: deploy
    if: branch = support/travis-ci
    env:
      - NODE_ENV=production
      - CLOUDSDK_CORE_DISABLE_PROMPTS=1

install: true

script: cd $PROJECT_DIR && npm install && npm test

before_deploy: chmod +x ../scripts/before-deploy.sh && ../scripts/before-deploy.sh

deploy:
  provider: script
  script: chmod +x ../scripts/deploy-k8s.sh && ../scripts/deploy-k83.sh
  skip_cleanup: true
  on:
    branch: support/travis-ci
