POST http://0.0.0.0:8080/api/jobapplication/1/comment
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwiaWF0IjoxNTQzMDg2ODk1fQ.jYMjGDg_bv6_nQ1Kbo75zU6_asdowjvRxvfEXcRRKZA

{
    "comment": "AAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaaAAaaaaaaaaaaaaaaaaa"
}
