POST http://0.0.0.0:8080/api/jobapplication/1/comment
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6MSwiaWF0IjoxNTQzMDQ4MTA1fQ.1iW4zhwlJjQXVQlVDP7xBnqXxvWN43bWAWjp5ItU4J4

{
    "comment": "Vielä yksi."
}
